name: Convert Excel to PDF and JPG

on:
  push:
    paths:
      - '**/*.xlsx'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl matplotlib reportlab

    - name: Convert Excel to PDF and JPG
      run: |
        python convert_excel.py

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Commit changes
      run: |
        git checkout -b convert-output
        git add *.pdf *.jpg
        git commit -m "Add converted PDF and JPG of the first worksheet"

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push -u origin convert-output

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: convert-output
        title: "Update converted files"
        body: "This PR updates the PDF and JPG files generated from the first worksheet of the Excel file."
